services:
  limbo:
    image: us-central1-docker.pkg.dev/molten-verve-216720/turso-repository/limbo-workload:antithesis-latest
    environment:
      SANDBOX: "composed"
    command: ["sleep", "infinity"]
