[package]
name = "turso-sync"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
turso_core = { workspace = true }
turso = { workspace = true }
thiserror = "2.0.12"
tracing = "0.1.41"
hyper = { version = "1.6.0", features = ["client", "http1"] }
serde_json.workspace = true
http-body-util = "0.1.3"
http = "1.3.1"
hyper-util = { version = "0.1.16", features = ["tokio", "http1", "client"] }
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1.46.1", features = ["fs", "io-util"] }
hyper-rustls = { version = "0.27.7", default-features = false, features = ["rustls-native-certs", "http1", "ring"] }

[dev-dependencies]
ctor = "0.4.2"
tempfile = "3.20.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread", "test-util"] }
uuid = "1.17.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
futures = "0.3.31"
paste = "1.0.15"
